#!/bin/bash

_vvplot(){
	COMPREPLY=()
	cur="${COMP_WORDS[COMP_CWORD]}"

	if [[ ${COMP_CWORD} == 1 ]]
	then
		COMPREPLY=($(compgen -f -X '!*.h5' -o plusdirs  -- ${cur}))
	else
		case "$cur" in
			-*)
				COMPREPLY=($(compgen -W '-b -f -g -h -H -i -n -O -p -P -s -t \
					-v -V -w -x -y --blankbody --size --nooverride --referenceframe \
					--streamlines --pressure --colorbox --timelabel --spring\
					--force --grayscale'  -- ${cur}));;
			*)
				COMPREPLY=($(compgen -f -X '!*.png' -o plusdirs  -- ${cur}));;
		esac
	fi

	return 0
}

bash_completion='for i in $(ls ~/.bash_completion.d/); do . ~/.bash_completion.d/$i; done'

_install_vvplot_completion(){
	[[ ! -e ~/.bash_completion ]] && echo "$bash_completion" > ~/.bash_completion
	[[ ! -e ~/.bash_completion.d/ ]] && mkdir ~/.bash_completion.d/
	cp completion_vvplot ~/.bash_completion.d/vvplot
}

_uninstall_vvplot_completion(){
	rm -f ~/.bash_completion.d/vvplot
}

complete -F _vvplot -o filenames vvplot

