#!/bin/bash

if test $# -lt 1
then
	echo "Usage: $0 file.vb [bookmarks]"
	echo "If no bookmarks are given, list of them is printed"
	exit 0
fi

if test $# -lt 2
then
	for ((i=1; i<64; i++))
	do
		BMname=$(head -c$(expr $i \* 16 + 16)  $1 | tail -c8);
		if test -n "$BMname"
		then
			beg=$(od -j$(expr $i \* 16) -N8 -An -w8 -td8 $1)
			N=$(od -j$beg -N8 -An -w8 -td8 $1)
			printf "%2d: %-8s @ %d [N=%d]\n" $i $BMname $beg $N
		fi
#		od -j$(expr $i \* 16 + 8) -N8 -An -w8 -ta $1
	done

	exit 0
fi

file=$1
shift
for i in $@
do
	beg=$(od -j$(expr $i \* 16) -N8 -An -w8 -td8 $file)
	size=$(od -j$beg -N8 -An -w8 -td8 $file)
	od -j$(expr $beg + 8) -N$(expr $size \* 24) -w24 -An -tf8 $file
done
