#!/bin/bash

exif_cmd="$0 $*"
while test "${1:0:1}" = "-"
do
	options="$options${1:1}"
	shift
done

if test $# -lt 4
then
	echo "Usage: $0 -[bfhiopstv01] file.vb output.png xmin xmax [y_offset]"
	echo "Possible options are:"
	echo "-b - plot Body"
	echo "-f - update Fields files even if the exist"
	echo "-h - plot Heat particles"
	echo "-i - plot Ink (streaklines)"
	echo "-o - plot isOtherms"
	echo "-p - plot Pressure field"
	echo "-s - plot Streamlines"
	echo "-t - plot Temperature field"
	echo "-v - plot Vortex domains"
	echo "-0 - change reference frame connected with fluid"
	echo "-1 - reference frame, steady moving relative fluid at rate (-1, 0)"
	echo "if neither -0 nor -1 are mentioned - body reference frame is present (as in computation)"

	echo "Additional environmental variables:"
	echo 'VV_ISOPSI - streamlines levels (default $(seq -s ' ' -10 0.1 10))'
	echo 'VV_ISOTHERMS - temperature isolines (default $(seq -s ' ' 0.05 0.05 0.95))'
	echo 'HEATPLOT_EPS_MULT - smooth temperature field picture (default 2)'
	echo 'HEATPLOT_BODY_TEMP - body surface temperature (default 1)'
	exit 0
fi

if test ! -e $1; then echo "No such file or directory: $1" >&2; exit -2; fi

v_skip=$(od -j16 -N8 -An -w8 -td8 $1)
v_size=$(od -j$v_skip -N8 -An -w8 -td8 $1)
h_skip=$(od -j32 -N8 -An -w8 -td8 $1)
h_size=$(od -j$h_skip -N8 -An -w8 -td8 $1)
i_skip=$(od -j64 -N8 -An -w8 -td8 $1)
i_size=$(od -j$i_skip -N8 -An -w8 -td8 $1)

time=$(printf "%7.3f\n" $(od -j$(expr $v_skip - 8) -N8 -tf8 -w8 -An $1) )
timestamp=$(od -j$(expr $v_skip - 16) -N8 -td8 -w8 -An $1)
realtime=$(date -d "1970-01-01 $timestamp sec GMT" +"%F %H:%M:%S")
dt=$(printf "%g" $(od -j$(expr $v_skip - 48) -N8 -tf8 -w8 -An $1) )
Re=$(printf "%g" $(od -j$(expr $v_skip - 40) -N8 -tf8 -w8 -An $1) )
vx=$(printf "%g" $(od -j$(expr $v_skip - 32) -N8 -tf8 -w8 -An $1) )
vy=$(printf "%g" $(od -j$(expr $v_skip - 24) -N8 -tf8 -w8 -An $1) )

x_offset=0
if test $i_size -ge 1
then
	x_marker=$(od -j$(expr $i_skip + 8) -N8 -w8 -An -tf8 $1)
	if test $(expr index "$options" 0) -ne 0
	then
		x_offset="$x_marker - 1000"
	elif test $(expr index "$options" 1) -ne 0
	then
		x_offset="$x_marker - 1000 - $time"
	fi
fi

if test -z "$5"
then
	y_offset="0"
else
	y_offset="$5"
fi

pipe="/tmp/pipe.$$.tmp"
mkfifo $pipe
gnuplot $pipe &
exec 6>$pipe #its very important to work through fd, because else it doesnt work

echo "set terminal pngcairo enhanced size 1280, 720 font \"FreeSerif, 26\"" >&6
echo "set output '$2'" >&6

echo "
unset key
set lmargin 0
set rmargin 0
set bmargin 0
set tmargin 0
set border 0
set zeroaxis
unset xtics
unset ytics
" >&6

echo "
set macros
xmin = $3 - ($x_offset);    xmin_c = sprintf(\"%f\", xmin);
xmax = $4 - ($x_offset);    xmax_c = sprintf(\"%f\", xmax);
ymin = -($4-$3)*9./32. - ($y_offset); ymin_c = sprintf(\"%f\", ymin);
ymax =  ($4-$3)*9./32. - ($y_offset); ymax_c = sprintf(\"%f\", ymax);
prec_hi = ($4-$3)/500.;      prec_hi_c = sprintf(\"%f\", prec_hi);
prec_lo = ($4-$3)/200.;      prec_lo_c = sprintf(\"%f\", prec_lo);
set xrange [xmin: xmax]
set yrange [ymin: ymax]
set colorbox horizontal user origin .1,.02 size .8,.04
" >&6

echo "
set label \"t = $time\" at graph 0.05, 0.90 front
dots = \"dots lc rgb variable\"
vortex_style = \"circles lc rgb variable fs transparent solid 0.3 noborder\"
heat_style = \"circles lc rgb 'black' fs transparent solid 0.3 noborder\"
ink_style = \"circles lc rgb 'black' fs transparent solid 1 noborder\"
body_style = \"filledcurve lc rgb \\\"#adadad\\\" lw 2 fs solid border -1 \"

color(x) = (x>0) ? 0xFF0000 : 0x0000FF
isoline(C) = sprintf(\"< isoline_exe $1.psi %s %f %f %f %f %f\", C, prec_lo, xmin, xmax, ymin, ymax)
" >&6

if test $(expr index "$options" p) != 0; then
echo "set cbrange [-1.5:1]" >&6
echo "set label \"-1.5\" at graph 0.096, 0.039 right front" >&6
echo "set label \"1\" at graph 0.904, 0.039 left front" >&6
echo "set palette maxcolors 33 defined (-1.5 \"#0829d5\", -0.5 \"#1ffcff\", 0 \"#2ef62e\", 0.3 \"yellow\", 1 \"red\")" >&6
if test ! -e $1.map -o $(expr index "$options" f) != 0; then
echo "\`presplot_exe $1 @prec_hi_c @xmin_c @xmax_c @ymin_c @ymax_c\`" >&6
fi; fi;

if test $(expr index "$options" t) != 0; then
echo "set cbrange [0:1]" >&6
echo "set label \"0\" at graph 0.096, 0.039 right front" >&6
echo "set label \"1\" at graph 0.904, 0.039 left front" >&6
echo "set palette maxcolors 33 defined (0 \"#0829d5\", 0.3 \"#1ffcff\", 0.5 \"red\", 1 \"yellow\", 2 \"white\")" >&6
fi

if test $(expr index "$options" o) != 0 -o  $(expr index "$options" t) != 0; then
if test ! -e $1.heat -o $(expr index "$options" f) != 0; then
echo "\`heatplot_exe $1 @prec_hi_c @xmin_c @xmax_c @ymin_c @ymax_c\`" >&6
fi; fi;

if test $(expr index "$options" s) != 0; then
if test ! -e $1.psi -o $(expr index "$options" f) != 0; then
echo "\`streamlines_exe $1 @prec_lo_c @xmin_c @xmax_c @ymin_c @ymax_c B\`" >&6
fi; fi;

echo -n "plot \"-\"" >&6

if test $(expr index "$options" p) != 0; then echo -n ", '$1.map' w image" >&6; fi
if test $(expr index "$options" t) != 0; then echo -n ", '$1.heat' w image" >&6; fi
if test $(expr index "$options" v) != 0 -a $v_size -gt 0
then
	echo -n ", '$1' binary record=$v_size skip=($v_skip+8) format='%3float64' " >&6
	echo -n "u 1:2:(prec_hi):(color(\$3)) w @vortex_style" >&6
fi

if test $(expr index "$options" h) != 0 -a $h_size -gt 0
then
	echo -n ", '$1' binary record=$h_size skip=($h_skip+8) format='%3float64' " >&6
	echo -n "u 1:2:(prec_hi) w @heat_style" >&6
fi

if test $(expr index "$options" i) != 0 -a $i_size -gt 0
then
	echo -n ", '$1' binary record=$i_size skip=($i_skip+8) format='%3float64' " >&6
	echo -n "u 1:2:(prec_hi) w @ink_style" >&6
fi

if test $(expr index "$options" s) != 0; then
if test -z "$VV_ISOPSI"; then VV_ISOPSI=$(seq -s ' ' -10 0.1 10); fi
echo -n ",\"< isoline_exe $1.psi $VV_ISOPSI\" w lines lw 2 lc rgb \"#000000\"" >&6
fi

if test $(expr index "$options" o) != 0; then
if test -z "$VV_ISOTHERMS"; then VV_ISOTHERMS=$(seq -s ' ' 0.05 0.05 0.95); fi
echo -n ",\"< isoline_exe $1.heat $VV_ISOTHERMS\" w lines lw 2 lc rgb \"#000000\"" >&6
fi

if test $(expr index "$options" b) != 0; then
for ((i=5; i<10; i++)); do
	BMname=$(head -c$(expr $i \* 16 + 16)  $1 | tail -c8);
	if test "$BMname" = "Body" -o "$BMname" = "Body    "
	then
		beg=$(od -j$(expr $i \* 16) -N8 -An -w8 -td8 $1)
		N=$(od -j$beg -N8 -An -w8 -td8 $1)
		echo -n ", '$1' binary record=$N skip=($beg+8) format='%3float64' u 1:2 w @body_style" >&6
	fi
done
fi

echo -e "\n0 0\ne\nquit\n" >&6

exec 6>&-
rm $pipe
wait

comment=$(echo -en "time = $time; dt = $dt; Re = $Re; Vx = $vx; Vy = $vy;
Command = '$exif_cmd'")
exiv2 \
-M"set Exif.Photo.DateTimeOriginal $realtime" \
-M"set Exif.Image.DateTime $realtime" \
-M"set Exif.Photo.UserComment charset=Ascii $comment" $2


