#!/bin/bash

while test "${1:0:1}" = "-"
do
	options="$options${1:1}"
	shift
done

if test $# -lt 4
then
	echo "Usage: $0 [options] file.vb output.png xmin xmax"
	exit 0
fi

v_skip=$(od -j16 -N8 -An -w8 -td8 $1)
v_size=$(od -j$v_skip -N8 -An -w8 -td8 $1)

time=$(printf "%7.3f\n" $(od -j$(expr $v_skip - 8) -N8 -tf8 -w8 -An $1) )
timestamp=$(od -j$(expr $v_skip - 16) -N8 -td8 -w8 -An $1)
realtime=$(date -d "1970-01-01 $timestamp sec GMT" +"%F %H:%M:%S")
dt=$(printf "%g" $(od -j$(expr $v_skip - 48) -N8 -tf8 -w8 -An $1) )
Re=$(printf "%g" $(od -j$(expr $v_skip - 40) -N8 -tf8 -w8 -An $1) )
vx=$(printf "%g" $(od -j$(expr $v_skip - 32) -N8 -tf8 -w8 -An $1) )
vy=$(printf "%g" $(od -j$(expr $v_skip - 24) -N8 -tf8 -w8 -An $1) )

exec 3> >(gnuplot)

echo "unset key
set colorbox horizontal user origin .1,.02 size .8,.04
set macros
ymax = ($4-$3)*9./32.
prec = ($4-$3)/500.
prec2 = ($4-$3)/200.
prec_c = sprintf(\"%f\", prec)
prec2_c = sprintf(\"%f\", prec2)
ymax_c = sprintf(\"%f\", ymax)
set xrange [$3: $4]
set yrange [($3-$4)*9./32.: ($4-$3)*9./32.]
set cbrange [-1.5:1]

set terminal pngcairo enhanced size 1280, 720 font \"FreeSerif, 26\"
set output '$2'

set lmargin 0; set rmargin 0; set bmargin 0; set tmargin 0;
set border 0;
set zeroaxis;
unset xtics; unset ytics;

set label \"t = $time\" at graph 0.05, 0.90 front

set macros
dots = \"dots lc rgb variable\"
vortex_style = \"circles lc rgb variable fs transparent solid 0.3 noborder\"
body_style = \"filledcurve lc rgb \\\"#adadad\\\" lw 2 fs solid border -1 \"

set palette color
set palette maxcolors 33 defined (-1.5 \"#0829d5\", -0.5 \"#1ffcff\", 0 \"#2ef62e\", 0.3 \"yellow\", 1 \"red\")
rgb(r,g,b) = 65536 * int(r) + 256 * int(g) + int(b)
color(x) = (x>0) ? rgb(255,0,0) : rgb(0,0,255)
isoline(C) = sprintf(\"< isoline_exe $1.psi %s %f $3 $4 %f %f\", C, @prec2_c, -@ymax_c, @ymax_c)" >&3

if test $(expr index "$options" p) != 0; then
if test ! -e $1.map -o $(expr index "$options" f) != 0; then
echo "\`presplot_exe $1 @prec_c $3 $4 -@ymax_c @ymax_c\`" >&3
fi; fi;

if test $(expr index "$options" s) != 0; then
if test ! -e $1.psi -o $(expr index "$options" f) != 0; then
echo "\`streamlines_exe $1 @prec2_c $3 $4 -@ymax_c @ymax_c\`" >&3
fi; fi;

echo -n "plot \"-\"" >&3

if test $(expr index "$options" p) != 0; then echo -n ", '$1.map' w image" >&3; fi
if test $(expr index "$options" v) != 0
then
	echo -n ", '$1' binary record=$v_size skip=($v_skip+8) format='%3float64' u 1:2:(prec):(color(\$3)) w @vortex_style" >&3
fi

if test $(expr index "$options" s) != 0; then
echo -n ", for [i in \"$(seq -s ' ' -1 0.04 1) $VV_ISOLINES\"] isoline(i) w lines lw 2 lc rgb \"#000000\"" >&3
fi

if test $(expr index "$options" b) != 0; then
for ((i=5; i<10; i++)); do
	BMname=$(head -c$(expr $i \* 16 + 16)  $1 | tail -c8);
	if test "$BMname" = "Body"
	then
		beg=$(od -j$(expr $i \* 16) -N8 -An -w8 -td8 $1)
		N=$(od -j$beg -N8 -An -w8 -td8 $1)
		echo -n ", '$1' binary record=$N skip=($beg+8) format='%3float64' u 1:2 w @body_style" >&3
	fi
done
fi

echo -e "\n0 0\ne\n" >&3
comment="time = $time; dt = $dt; Re = $Re; Vx = $vx; Vy = $vy;"
echo "\`exiv2 -M\"set Exif.Photo.DateTimeOriginal $realtime\" \
-M\"set Exif.Image.DateTime $realtime\" \
-M\"set Exif.Photo.UserComment charset=Ascii $comment\" $2\`" >&3

exec 3>&-
