#!/bin/bash

if test $# -lt 1
then
	echo "Usage: $0 file.vb [bookmarks]"
	echo "If no bookmarks are given, list of them is printed"
	exit 0
fi

if test $# -lt 2
then
	v_skip=$(od -j16 -N8 -An -w8 -td8 $1)
	time=$(printf "%7.3f\n" $(od -j$(expr $v_skip - 8) -N8 -tf8 -w8 -An $1) )
	timestamp=$(od -j$(expr $v_skip - 16) -N8 -td8 -w8 -An $1)
	realtime=$(date -d "1970-01-01 $timestamp sec GMT" +"%F %H:%M:%S")
	dt=$(printf "%g" $(od -j$(expr $v_skip - 48) -N8 -tf8 -w8 -An $1) )
	Re=$(printf "%g" $(od -j$(expr $v_skip - 40) -N8 -tf8 -w8 -An $1) )
	vx=$(printf "%g" $(od -j$(expr $v_skip - 32) -N8 -tf8 -w8 -An $1) )
	vy=$(printf "%g" $(od -j$(expr $v_skip - 24) -N8 -tf8 -w8 -An $1) )

	printf "Time  = %g\ndt    = %g\nVinf  = (%g, %g)\n" $time $dt $vx $vy
	printf "1/Nyu = %g\nDate  = %s\n\n" $Re "$realtime"

	for ((i=1; i<64; i++))
	do
		BMname=$(head -c$(expr $i \* 16 + 16)  $1 | tail -c8);
		if test -n "$BMname"
		then
			beg=$(od -j$(expr $i \* 16) -N8 -An -w8 -td8 $1)
			N=$(od -j$beg -N8 -An -w8 -td8 $1)
			printf "%2d: %-8s @ %d [N=%d]\n" $i $BMname $beg $N
		fi
#		od -j$(expr $i \* 16 + 8) -N8 -An -w8 -ta $1
	done

	exit 0
fi

file=$1
shift
for i in $@
do
	beg=$(od -j$(expr $i \* 16) -N8 -An -w8 -td8 $file)
	size=$(od -j$beg -N8 -An -w8 -td8 $file)
	od -j$(expr $beg + 8) -N$(expr $size \* 24) -w24 -An -tf8 $file
done
