#!/bin/bash

_vvcompose(){
	COMPREPLY=()
	cur="${COMP_WORDS[COMP_CWORD]}"

	case "$3" in
		"load") COMPREPLY=($(compgen -W 'hdf body vort heat ink ink_source' -- ${cur}));;
		"set") COMPREPLY=($(compgen -W '
			caption time dt dt_save dt_streak dt_profile
			re pr inf_speed.x inf_speed.y inf_circulation
			time_to_finish gravity.x gravity.y
			bodyXX.speed.x bodyXX.speed.y bodyXX.speed.o
			bodyXX.root_body bodyXX.density
			bodyXX.move.x bodyXX.move.y bodyXX.move.o bodyXX.move.d
			bodyXX.holder_position.x bodyXX.holder_position.y
			bodyXX.holder_position.o bodyXX.holder_position.d
			bodyXX.delta_position.x bodyXX.delta_position.y
			bodyXX.delta_position.o bodyXX.delta_position.d
			bodyXX.spring_const.x bodyXX.spring_const.y
			bodyXX.spring_const.o bodyXX.spring_damping.x
			bodyXX.spring_damping.y bodyXX.spring_damping.o
			bodyXX.general_slip bodyXX.special_segment_no
			bodyXX.boundary_condition bodyXX.heat_condition
			bodyXX.heat_const' -- ${cur}));;
		"del") COMPREPLY=($(compgen -W 'vort heat ink ink_source body00' -- ${cur}));;
		"save") COMPREPLY=($(compgen -f -X '!*.h5' -o plusdirs  -- ${cur}));;
		"hdf") COMPREPLY=($(compgen -f -X '!*.h5' -o plusdirs  -- ${cur}));;
		*) COMPREPLY=($(compgen -W 'load set del save' -- ${cur}));;
	esac

	return 0
}

bash_completion='for i in $(ls ~/.bash_completion.d/); do . ~/.bash_completion.d/$i; done'

_install_vvcompose_completion(){
	[[ ! -e ~/.bash_completion ]] && echo "$bash_completion" > ~/.bash_completion
	[[ ! -e ~/.bash_completion.d/ ]] && mkdir ~/.bash_completion.d/
	cp completion_vvcompose ~/.bash_completion.d/vvcompose
}

_uninstall_vvcompose_completion(){
	rm -f ~/.bash_completion.d/vvcompose
}

complete -F _vvcompose -o filenames vvcompose

