all:
	g++ vorticitydensity.cpp -o vorticitydensity -g -lVVHDcore -lVVHDmodules

install:
	cp vorticitydensity /usr/local/bin

uninstall:
	rm -f /usr/local/bin/vorticitydensity

clean:
	rm -f vorticitydensity
