#!/bin/bash

TMP=$(mktemp -d)
#echo create temp: $TMP
H5F="$1"
PASTE=()

i=0
for D in "${@:2}"
do
#	echo extract \"$D\" from \"$H5F\"
	TMPD=$(mktemp --tmpdir=$TMP)
	echo "# $D" > $TMPD
	h5totxt -d "$D" -. 8 -s$'\t' $H5F >> $TMPD
	PASTE[$i]=$TMPD
	i=$(($i + 1))
done
paste "${PASTE[@]}"
rm -rf $TMP
