name: Vvflow CI

on:
  push:

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install dependencies
      run: |
        sudo apt-get install liblapack-dev gnuplot
        pip3 install -r pytest/requirements.txt

    - name: Cache CMakeFiles
      uses: actions/cache@v2
      with:
        path: |
          build/*
          ~build/deb
        key: bionic-cmake-cache-02

    - run: mkdir -p build
    - run: cmake ..
      working-directory: ./build
    - run: make -j
      working-directory: ./build
    - run: ctest -VV
      working-directory: ./build
    - run: cpack
      working-directory: ./build
    - run: ls -al build/deb/vvflow-*.deb

    - name: Upload to packagecloud/nightly
      if: >
        github.ref == 'refs/heads/master' ||
        startsWith(github.ref, 'refs/tags/')
      run: >
        curl
        -u "${{ secrets.PACKAGECLOUD_TOKEN }}:"
        -F "package[distro_version_id]=190"
        -F "package[package_file]=@$(ls build/deb/vvflow-*.deb | tail -n1)"
        -v https://packagecloud.io/api/v1/repos/vvflow/nightly/packages.json

    - name: Upload to packagecloud/stable
      if: startsWith(github.ref, 'refs/tags/')
      run: >
        curl
        -u "${{ secrets.PACKAGECLOUD_TOKEN }}:"
        -F "package[distro_version_id]=190"
        -F "package[package_file]=@$(ls build/deb/vvflow-*.deb | tail -n1)"
        -v https://packagecloud.io/api/v1/repos/vvflow/stable/packages.json
